
import type { MenuItem } from '@/lib/types';

export const menuSeedData: Omit<MenuItem, '_id'>[] = [
    {
        name: "Chocolate Truffle Cake",
        category: "Cakes",
        price: 800,
        priceUnit: "per cake",
        image: "https://media.istockphoto.com/id/1709425121/photo/chocolate-cake-with-chocolate-fudge-drizzled-on-top.webp?b=1&s=170667a&w=0&k=20&c=KxR2s6yghlqHfY2c50jG14S-bL3l3v3pZq5y5_d-YlU=",
        hint: "chocolate cake",
        dietary: ["Eggless"],
        isFeatured: true,
    },
    {
        name: "Classic Ladoo",
        category: "Sweets",
        price: 300,
        priceUnit: "/kg",
        image: "https://media.istockphoto.com/id/1222473094/photo/sweet-motichoor-laddoo-also-known-as-motichur-ke-ladu-is-a-popular-indian-sweet-made-from.webp?b=1&s=170667a&w=0&k=20&c=3Z-p5rsoXkLsvj2i21_36BAb4KVmNNaJ4t_YCWzGvO8=",
        hint: "ladoo sweet",
        dietary: ["Gluten-Free"],
        isFeatured: true,
    },
    {
        name: "Kaju Katli",
        category: "Sweets",
        price: 1000,
        priceUnit: "/kg",
        image: "https://media.istockphoto.com/id/1441530948/photo/kaju-katli-is-a-popular-indian-sweet-made-from-cashews-and-sugar-it-is-a-diamond-shaped.webp?b=1&s=170667a&w=0&k=20&c=6i-Q3GfDM7-x8L09F-T8z-J4W3fYEjFSm5_2CjL5z5Q=",
        hint: "kaju katli",
        dietary: ["Gluten-Free"],
        isFeatured: true,
    },
    {
        name: "Iced Lemon Tea",
        category: "Drinks",
        price: 80,
        priceUnit: "per glass",
        image: "https://media.istockphoto.com/id/526422899/photo/iced-tea.webp?b=1&s=170667a&w=0&k=20&c=p-bSajh0b3q-T4Sg2F1FPAJCYsM8L2aB-VGo8Gu-32I=",
        hint: "iced tea",
        dietary: ["Vegan"],
        isFeatured: true,
    },
    {
        name: "Pineapple Pastry",
        category: "Cakes",
        price: 120,
        priceUnit: "per piece",
        image: "https://media.istockphoto.com/id/1410185955/photo/close-up-of-pineapple-cake-on-plate.webp?b=1&s=170667a&w=0&k=20&c=L_YV_P2L-HGsG5p-6k-m8C_I63rttnO1x6vPz-U8-3g=",
        hint: "pineapple pastry",
        dietary: [],
        isFeatured: false,
    },
    {
        name: "Crispy Samosa",
        category: "Snacks",
        price: 20,
        priceUnit: "per piece",
        image: "https://media.istockphoto.com/id/1344793836/photo/samosa-a-popular-indian-snack.webp?b=1&s=170667a&w=0&k=20&c=vWf5tBq6LzsgTAlL0KjCq7hL6y0xKx2-cM2qV52Fk6E=",
        hint: "samosa snack",
        isFeatured: false,
    },
    {
        name: "Gulab Jamun",
        category: "Sweets",
        price: 250,
        priceUnit: "/kg",
        image: "https://media.istockphoto.com/id/1157175424/photo/gulab-jamun-in-white-bowl-with-spoon-indian-sweet-dish.webp?b=1&s=170667a&w=0&k=20&c=4UazG2sHY44hmgputvNnIM1CI2Di2JvI-sOQ8t0YhPA=",
        hint: "gulab jamun",
        dietary: ["Gluten-Free"],
        isFeatured: false,
    },
];
